# Generated by Django 3.0.3 on 2020-03-18 09:15

import apps.dashboard.models
import django.core.validators
from django.db import migrations, models
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, storage=utils.custom_storage.MediaStorage(), upload_to=apps.dashboard.models.generate_banner_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'pjpeg', 'png', 'svg']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity], verbose_name='Display Picture')),
                ('banner_type', models.CharField(blank=True, choices=[('HomeCollection', 'HomeCollection')], max_length=14, null=True, verbose_name='Banner Type')),
            ],
            options={
                'verbose_name': 'Dashboard Banner',
                'verbose_name_plural': 'Dashboard Banners',
            },
        ),
    ]
