# Generated by Django 3.0.3 on 2021-03-25 12:32

import apps.dashboard.models
import django.core.validators
from django.db import migrations, models
import django_clamd.validators
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200318_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('banner', 'Banner'), ('description', 'Description'), ('qna', 'QnA'), ('video', 'Video')], default='qna', max_length=15)),
                ('code', models.SlugField(unique=True)),
                ('question', models.TextField()),
                ('data', models.TextField()),
                ('image', models.ImageField(storage=utils.custom_storage.MediaStorage(), upload_to=apps.dashboard.models.generate_faq_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'pjpeg', 'png', 'svg']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity, django_clamd.validators.validate_file_infection], verbose_name='FAQ Picture')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='dashboardbanner',
            name='image',
            field=models.ImageField(storage=utils.custom_storage.MediaStorage(), upload_to=apps.dashboard.models.generate_banner_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'pjpeg', 'png', 'svg']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity, django_clamd.validators.validate_file_infection], verbose_name='Display Picture'),
        ),
    ]
