# Generated by Django 3.0.3 on 2021-05-21 18:25

import apps.dashboard.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_clamd.validators
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_flyerscheduler'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlyerImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Sequence', models.IntegerField()),
                ('image', models.ImageField(storage=utils.custom_storage.MediaStorage(), upload_to=apps.dashboard.models.generate_flyer_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'pjpeg', 'png', 'svg']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity, django_clamd.validators.validate_file_infection], verbose_name='Flyer Picture')),
                ('learn_more_url', models.TextField(blank=True, max_length=1000, null=True)),
                ('learn_more_url_text', models.CharField(blank=True, max_length=100, null=True)),
                ('learn_more_url_color', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='create_by_base_user', to=settings.AUTH_USER_MODEL)),
                ('flyer_scheduler_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Flyer_scheduler', to='dashboard.FlyerScheduler')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_by_base_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
