# Generated by Django 3.0.3 on 2021-05-24 11:56

import apps.dashboard.models
import django.core.validators
from django.db import migrations, models
import django_clamd.validators
import utils.custom_storage
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210521_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flyerimages',
            name='Sequence',
        ),
        migrations.AddField(
            model_name='flyerimages',
            name='sequence',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='flyerimages',
            name='image',
            field=models.ImageField(storage=utils.custom_storage.MediaStorage(), upload_to=apps.dashboard.models.generate_flyer_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'pjpeg', 'png', 'svg']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity, django_clamd.validators.validate_file_infection], verbose_name='Flyer_picture'),
        ),
        migrations.AlterField(
            model_name='flyerimages',
            name='learn_more_url',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flyerimages',
            name='learn_more_url_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flyerimages',
            name='learn_more_url_text',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='flyerscheduler',
            name='frequency',
            field=models.CharField(choices=[('Once-a-Day', 'Once-a-Day'), ('EveryTime', 'EveryTime')], max_length=20),
        ),
    ]
