# Generated by Django 3.0.3 on 2021-05-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210524_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyerscheduler',
            name='frequency',
            field=models.CharField(choices=[('onceaday', 'Once-a-Day'), ('everytime', 'EveryTime')], max_length=20),
        ),
    ]
