# Generated by Django 3.0.3 on 2021-05-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210524_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyerscheduler',
            name='frequency',
            field=models.IntegerField(choices=[(0, 'Once-a-Day'), (1, 'EveryTime')], max_length=20),
        ),
    ]
