# Generated by Django 3.0.3 on 2021-05-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210525_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flyerimages',
            old_name='learn_more_url_color',
            new_name='learn_more_url_button_color',
        ),
        migrations.AddField(
            model_name='flyerimages',
            name='learn_more_url_text_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
