# Generated by Django 3.0.3 on 2021-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210528_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardbanner',
            name='banner_type',
            field=models.CharField(choices=[('HomeCollection', 'HomeCollection'), ('HomeCare', 'HomeCare')], default='HomeCollection', max_length=14, verbose_name='Banner Type'),
        ),
    ]
