# Generated by Django 3.0.5 on 2020-04-27 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0005_country_idproof_province_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='from_date',
            field=models.DateField(default=datetime.date(2020, 4, 27)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
