# Generated by Django 3.0.5 on 2020-04-27 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0006_auto_20200427_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
