# Generated by Django 3.0.5 on 2020-04-27 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0008_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Province',
        ),
    ]
