# Generated by Django 3.0.3 on 2021-10-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0057_appointment_slot_duration'),
        ('patients', '0047_auto_20211005_1453'),
        ('payments', '0035_payment_payment_for_drive'),
        ('home_care', '0001_initial'),
        ('master_data', '0040_helplinenumbers_title'),
        ('phlebo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestslotschedule',
            name='phlebo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phlebo.Phlebo'),
        ),
        migrations.AddField(
            model_name='labtestslotschedule',
            name='weekly_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home_care.LabTestSlotsWeeklyMaster'),
        ),
        migrations.AddField(
            model_name='labtestappointment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.PatientAddress'),
        ),
        migrations.AddField(
            model_name='labtestappointment',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.FamilyMember'),
        ),
        migrations.AddField(
            model_name='labtestappointment',
            name='health_tests',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home_care.HealthTest'),
        ),
        migrations.AddField(
            model_name='labtestappointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital'),
        ),
        migrations.AddField(
            model_name='labtestappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='labtestappointment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Payment'),
        ),
        migrations.AddField(
            model_name='labtestappointment',
            name='phlebo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='phlebo.Phlebo'),
        ),
        migrations.AddField(
            model_name='labtestappointment',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.CancellationReason'),
        ),
        migrations.AddField(
            model_name='hospitalregion',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital'),
        ),
        migrations.AddField(
            model_name='healthtestpricing',
            name='health_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_test', to='home_care.HealthTest'),
        ),
        migrations.AddField(
            model_name='healthtestpricing',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_test_hospital', to='master_data.Hospital'),
        ),
        migrations.AddField(
            model_name='healthtestcartitems',
            name='health_test',
            field=models.ManyToManyField(to='home_care.HealthTest'),
        ),
        migrations.AddField(
            model_name='healthtestcartitems',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital'),
        ),
        migrations.AddField(
            model_name='healthtestcartitems',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient_user', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='healthtest',
            name='billing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_care_billing_group', to='master_data.BillingGroup'),
        ),
        migrations.AddField(
            model_name='healthtest',
            name='billing_sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_care_billing_sub_group', to='master_data.BillingSubGroup'),
        ),
        migrations.AddField(
            model_name='healthtest',
            name='health_test_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='heath_test_category', to='home_care.HealthTestCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='healthtestpricing',
            unique_together={('health_test', 'hospital')},
        ),
    ]
