# Generated by Django 3.0.2 on 2020-01-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_tests', '0001_initial'),
        ('health_packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='included_health_tests',
            field=models.ManyToManyField(to='health_tests.HealthTest'),
        ),
    ]
