# Generated by Django 3.0.3 on 2020-03-05 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPackageCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Health Package Category',
                'verbose_name_plural': 'Health Package Categories',
            },
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='health_packages.HealthPackageCategory'),
        ),
    ]
