# Generated by Django 3.0.3 on 2020-03-10 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0004_auto_20200310_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackagepricing',
            name='health_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='health_package_pricing', to='health_packages.HealthPackage'),
        ),
    ]
