# Generated by Django 3.0.3 on 2020-03-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0005_auto_20200310_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='age_group',
            field=models.CharField(blank=True, default='All age groups', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='healthpackage',
            name='gender',
            field=models.CharField(blank=True, default='Men and Women', max_length=50, null=True),
        ),
    ]
