# Generated by Django 3.0.3 on 2020-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0006_auto_20200310_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Popular Health Package'),
        ),
    ]
