# Generated by Django 3.0.6 on 2020-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0009_remove_healthpackage_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackage',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Male and Female', 'Male and Female')], default='Male and Female', max_length=15, verbose_name='Gender'),
        ),
    ]
