# Generated by Django 3.0.3 on 2020-09-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0012_healthpackage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackage',
            name='image',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
