# Generated by Django 3.0.3 on 2020-09-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0013_auto_20200928_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackagepricing',
            name='discount_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthpackagepricing',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
