version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/mhe-backend/mhe-api-backend
hooks:
  BeforeInstall:
    - location: scripts/update.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/restart.sh
      timeout: 300
      runas: ec2-user
