# Generated by Django 3.0.3 on 2020-03-11 12:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patientaddress'),
        ('master_data', '0003_homecareservice'),
        ('lab_and_radiology_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientServiceAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_service_appointment', to='patients.PatientAddress')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_service_appointment', to='patients.FamilyMember')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_service_appointment', to='patients.Patient')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_service_appointment', to='master_data.HomeCareService')),
            ],
            options={
                'verbose_name': 'Patient Service Appointment',
                'verbose_name_plural': 'Patient Service Appointments',
            },
        ),
    ]
