# Generated by Django 3.0.3 on 2020-03-12 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20200312_1234'),
        ('lab_and_radiology_items', '0002_patientserviceappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientserviceappointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_service_appointment', to='patients.Patient'),
        ),
    ]
