# Generated by Django 3.0.3 on 2020-03-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_and_radiology_items', '0003_auto_20200312_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labradiologyitempricing',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_radiology_item_pricing', to='lab_and_radiology_items.LabRadiologyItem'),
        ),
    ]
