# Generated by Django 3.0.3 on 2020-03-14 10:13

import apps.lab_and_radiology_items.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20200312_1234'),
        ('lab_and_radiology_items', '0004_auto_20200314_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField()),
                ('document', models.FileField(storage=utils.custom_storage.FileStorage(), upload_to=apps.lab_and_radiology_items.models.generate_prescription_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xml', 'dotx', 'pdf', 'txt', 'xls', 'xlsx', 'csv', 'ppt', 'pps', 'ppsx', 'bmp', 'jpg', 'jpeg', 'pjpeg', 'gif', 'png', 'svg', 'html']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity])),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_prescription', to='patients.PatientAddress')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_prescription', to='patients.FamilyMember')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescription', to='patients.Patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
            },
        ),
    ]
