# Generated by Django 3.0.3 on 2020-03-16 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20200312_1234'),
        ('lab_and_radiology_items', '0005_uploadprescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCollectionAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_date', models.DateField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_home_collection_appointment', to='patients.PatientAddress')),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_home_collection_appointment', to='patients.FamilyMember')),
                ('home_collections', models.ManyToManyField(blank=True, to='lab_and_radiology_items.LabRadiologyItem')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_home_collection_appointment', to='patients.Patient')),
            ],
            options={
                'verbose_name': 'Home Collection Appointment',
                'verbose_name_plural': 'Home Collection Appointments',
            },
        ),
    ]
