# Generated by Django 3.0.3 on 2020-03-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_homecareservice'),
        ('lab_and_radiology_items', '0006_homecollectionappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecollectionappointment',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homecollectionappointment',
            name='home_collections',
            field=models.ManyToManyField(to='lab_and_radiology_items.LabRadiologyItem'),
        ),
    ]
