# Generated by Django 3.0.3 on 2020-03-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_and_radiology_items', '0007_auto_20200316_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecollectionappointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='patientserviceappointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='uploadprescription',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
    ]
