# Generated by Django 3.0.3 on 2020-03-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_and_radiology_items', '0008_auto_20200318_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientserviceappointment',
            name='appointment_date',
            field=models.DateField(),
        ),
    ]
