# Generated by Django 3.0.3 on 2020-03-22 13:33

import apps.lab_and_radiology_items.models
import django.core.validators
from django.db import migrations, models
import utils.custom_storage
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lab_and_radiology_items', '0009_auto_20200319_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadprescription',
            name='document',
        ),
        migrations.AddField(
            model_name='homecollectionappointment',
            name='document',
            field=models.FileField(blank=True, null=True, storage=utils.custom_storage.FileStorage(), upload_to=apps.lab_and_radiology_items.models.generate_prescription_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xml', 'dotx', 'pdf', 'txt', 'xls', 'xlsx', 'csv', 'ppt', 'pps', 'ppsx', 'bmp', 'jpg', 'jpeg', 'pjpeg', 'gif', 'png', 'svg', 'html']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity]),
        ),
    ]
