# Generated by Django 3.0.3 on 2020-03-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_hospital_is_home_collection_supported'),
        ('lab_and_radiology_items', '0011_auto_20200322_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecollectionappointment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital'),
        ),
    ]
