# Generated by Django 3.0.3 on 2020-03-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_and_radiology_items', '0012_auto_20200323_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecollectionappointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=9),
        ),
        migrations.AddField(
            model_name='patientserviceappointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=9),
        ),
    ]
