# Generated by Django 3.0.3 on 2020-03-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20200312_1234'),
        ('lab_and_radiology_items', '0014_auto_20200323_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecollectionappointment',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.CancellationReason'),
        ),
    ]
