# Generated by Django 3.0.3 on 2020-05-06 00:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_and_radiology_items', '0021_patientserviceappointment_final_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecollectionappointment',
            name='final_address',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
