# Generated by Django 3.0.3 on 2020-05-06 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_and_radiology_items', '0022_homecollectionappointment_final_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecollectionappointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='homecollectionappointment',
            name='final_address',
        ),
        migrations.RemoveField(
            model_name='patientserviceappointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patientserviceappointment',
            name='final_address',
        ),
    ]
