# Generated by Django 3.0.6 on 2020-05-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_homecareservice_image'),
        ('lab_and_radiology_items', '0025_auto_20200508_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientserviceappointment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital'),
        ),
    ]
