# Generated by Django 3.0.2 on 2020-01-17 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health_packages', '__first__'),
        ('health_tests', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'VisitAppointment',
                'verbose_name_plural': 'VisitAppointments',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField()),
                ('test_derived_cost', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
            },
        ),
        migrations.CreateModel(
            name='VisitTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=1)),
                ('total_test_cost', models.IntegerField()),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_tests.HealthTestPricing')),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.Visit')),
            ],
            options={
                'verbose_name': 'VisitTest',
                'verbose_name_plural': 'VisitTests',
            },
        ),
        migrations.CreateModel(
            name='VisitHealthPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_package_cost', models.IntegerField()),
                ('health_package_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_packages.HealthPackagePricing')),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.Visit')),
            ],
            options={
                'verbose_name': 'VisitHealthPackage',
                'verbose_name_plural': 'VisitHealthPackages',
            },
        ),
        migrations.CreateModel(
            name='VisitAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_cost', models.IntegerField()),
                ('visit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.Visit')),
            ],
            options={
                'verbose_name': 'VisitAppointment',
                'verbose_name_plural': 'VisitAppointments',
            },
        ),
    ]
