# Generated by Django 3.0.2 on 2020-01-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('billing', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='Doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.Doctor'),
        ),
        migrations.AddField(
            model_name='visit',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='cart',
            name='visit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.Visit'),
        ),
    ]
