# Generated by Django 3.0.2 on 2020-01-14 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0002_auto_20200114_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('remarks', models.TextField()),
                ('code', models.SlugField(blank=True, null=True, unique=True)),
                ('billing_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.BillingGroup')),
                ('billing_sub_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.BillingSubGroup')),
            ],
            options={
                'verbose_name': 'Health Test',
                'verbose_name_plural': 'Health Tests',
            },
        ),
        migrations.CreateModel(
            name='HealthTestPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('health_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='health_tests.HealthTest')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital')),
            ],
            options={
                'verbose_name': 'Health Test Pricing',
                'verbose_name_plural': 'Health Test Pricing',
            },
        ),
    ]
