# Generated by Django 3.0.3 on 2020-03-14 08:23

import apps.personal_documents.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0011_auto_20200312_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPersonalDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(storage=utils.custom_storage.FileStorage(), upload_to=apps.personal_documents.models.generate_personal_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xml', 'dotx', 'pdf', 'txt', 'xls', 'xlsx', 'csv', 'ppt', 'pps', 'ppsx', 'bmp', 'jpg', 'jpeg', 'pjpeg', 'gif', 'png', 'svg', 'html']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity])),
                ('patient_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_documents', to='patients.Patient')),
            ],
            options={
                'verbose_name': 'Patient Personal Document',
                'verbose_name_plural': 'Patient Personal Documents',
            },
        ),
    ]
