# Generated by Django 3.0.3 on 2020-04-07 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patient_new_mobile_verification_otp'),
        ('personal_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientpersonaldocuments',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_personal_documents', to='patients.FamilyMember'),
        ),
        migrations.AlterField(
            model_name='patientpersonaldocuments',
            name='patient_info',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='patient_documents', to='patients.Patient'),
            preserve_default=False,
        ),
    ]
