# Generated by Django 3.0.3 on 2021-10-11 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0040_helplinenumbers_title'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phlebo',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phlebo_hospital', to='master_data.Hospital')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='PhleboRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.CharField(max_length=10)),
                ('phlebo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phlebo', to='phlebo.Phlebo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
