# Generated by Django 3.0.3 on 2021-10-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phlebo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phlebo',
            name='mobile_verified',
            field=models.BooleanField(default=False, verbose_name='Mobile Verified'),
        ),
        migrations.AddField(
            model_name='phlebo',
            name='otp_expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Expiration Date Time'),
        ),
    ]
