# Generated by Django 3.0.3 on 2020-03-11 11:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_hospital_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCareService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Home Care Service',
                'verbose_name_plural': 'Home Care Services',
            },
        ),
    ]
