# Generated by Django 3.0.3 on 2020-02-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_auto_20200207_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinggroup',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billingsubgroup',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
