# Generated by Django 3.0.2 on 2020-02-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_auto_20200114_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='distance',
            field=models.IntegerField(blank=True, default=2.5),
        ),
    ]
