# Generated by Django 3.0.3 on 2020-02-28 08:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_hospital_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
