# Generated by Django 3.0.3 on 2020-03-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_homecareservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_home_collection_supported',
            field=models.BooleanField(default=False),
        ),
    ]
