# Generated by Django 3.0.3 on 2020-02-28 08:44

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_auto_20200228_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(1, 1), srid=4326),
        ),
    ]
