# Generated by Django 3.0.3 on 2020-05-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_ambulancecontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecareservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Display Picture'),
        ),
    ]
