# Generated by Django 3.0.3 on 2020-10-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0008_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='corporate_only',
            field=models.BooleanField(default=False),
        ),
    ]
