# Generated by Django 3.0.3 on 2020-10-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_hospital_corporate_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='hospital_info',
            field=models.ManyToManyField(blank=True, null=True, related_name='company_hospital', to='master_data.Hospital'),
        ),
    ]
