# Generated by Django 3.0.3 on 2020-11-09 13:11

import apps.master_data.models
import django.core.validators
from django.db import migrations, models
import utils.custom_storage
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_company_hospital_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecareservice',
            name='image',
            field=models.FileField(blank=True, null=True, storage=utils.custom_storage.FileStorage(), upload_to=apps.master_data.models.generate_service_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xml', 'dotx', 'pdf', 'txt', 'xls', 'xlsx', 'csv', 'ppt', 'pps', 'ppsx', 'bmp', 'jpg', 'jpeg', 'pjpeg', 'gif', 'png', 'svg', 'html']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity]),
        ),
    ]
