# Generated by Django 3.0.3 on 2020-11-11 11:36

import apps.master_data.models
import django.core.validators
from django.db import migrations, models
import utils.custom_storage
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0011_auto_20201109_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homecareservice',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storage.MediaStorage(), upload_to=apps.master_data.models.generate_service_file_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'pjpeg', 'png', 'svg']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity]),
        ),
    ]
