# Generated by Django 3.0.3 on 2021-01-27 14:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0014_emergencycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackRecipients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital_code', models.SlugField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('TO', 'TO'), ('CC', 'CC'), ('BCC', 'BCC')], max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Feedback recipient',
                'verbose_name_plural': 'Feedback recipients',
            },
        ),
    ]
