# Generated by Django 3.0.3 on 2021-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0016_auto_20210127_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldepartment',
            name='service',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hospitaldepartment',
            name='sub_service',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
