# Generated by Django 3.0.3 on 2021-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0017_auto_20210302_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='domain',
        ),
        migrations.AddField(
            model_name='company',
            name='domain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
