# Generated by Django 3.0.3 on 2021-03-15 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0018_auto_20210312_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='commponents',
            new_name='components',
        ),
    ]
