# Generated by Django 3.0.3 on 2021-03-25 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0020_auto_20210316_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_configs', models.ManyToManyField(blank=True, null=True, related_name='allowed_configuration', to='master_data.Components')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
