# Generated by Django 3.0.3 on 2021-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0021_configurations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configurations',
            name='allowed_configs',
        ),
        migrations.AddField(
            model_name='configurations',
            name='allowed_components',
            field=models.ManyToManyField(blank=True, null=True, related_name='allowed_component_ids', to='master_data.Components'),
        ),
    ]
