# Generated by Django 3.0.3 on 2021-03-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0022_auto_20210330_0949'),
        ('master_data', '0021_auto_20210326_1712'),
    ]

    operations = [
    ]
