# Generated by Django 3.0.3 on 2021-03-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0023_merge_20210330_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='code',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
