# Generated by Django 3.0.3 on 2021-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0024_components_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
