# Generated by Django 3.0.3 on 2021-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0025_company_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='hospital',
            name='promo_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
