# Generated by Django 3.0.3 on 2021-04-14 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0026_auto_20210405_1858'),
        ('master_data', '0017_auto_20210401_2152'),
    ]

    operations = [
    ]
