# Generated by Django 3.0.3 on 2021-04-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0013_language'),
        ('master_data', '0027_merge_20210414_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='family_members_relations',
            field=models.ManyToManyField(blank=True, null=True, related_name='corporate_family_relation', to='patient_registration.Relation'),
        ),
        migrations.AddField(
            model_name='company',
            name='is_family_members_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='number_of_family_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
