# Generated by Django 3.0.3 on 2021-04-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_merge_20210412_1813'),
        ('master_data', '0028_auto_20210414_1842'),
    ]

    operations = [
    ]
