# Generated by Django 3.0.3 on 2021-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0013_language'),
        ('master_data', '0028_auto_20210414_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='no_of_family_members',
            new_name='number_of_family_members',
        ),
        migrations.AlterField(
            model_name='company',
            name='family_members_relations',
            field=models.ManyToManyField(blank=True, null=True, related_name='corporate_family_relation', to='patient_registration.Relation'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_family_members_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
