# Generated by Django 3.0.3 on 2021-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0029_merge_20210426_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='family_members_components',
            field=models.ManyToManyField(blank=True, null=True, related_name='corporate_family_member_components', to='master_data.Components'),
        ),
    ]
