# Generated by Django 3.0.3 on 2021-04-28 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0030_company_family_members_components'),
        ('master_data', '0029_merge_20210426_1305'),
    ]

    operations = [
    ]
