# Generated by Django 3.0.3 on 2021-05-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0027_merge_20210414_1842'),
        ('master_data', '0031_merge_20210428_1328'),
    ]

    operations = [
    ]
