# Generated by Django 3.0.3 on 2021-05-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0032_merge_20210521_1523'),
        ('master_data', '0027_merge_20210414_1842'),
    ]

    operations = [
    ]
