# Generated by Django 3.0.3 on 2021-06-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0034_billing_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
