# Generated by Django 3.0.3 on 2021-06-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0035_auto_20210611_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='code',
            field=models.SlugField(default='<function uuid4 at 0x7f7f3a5d11f0>'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='code',
            field=models.SlugField(default='<function uuid4 at 0x7f7f3a5d11f0>'),
        ),
    ]
