# Generated by Django 3.0.3 on 2021-06-18 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0036_auto_20210618_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='code',
            field=models.SlugField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='code',
            field=models.SlugField(default=uuid.uuid4),
        ),
    ]
