# Generated by Django 3.0.3 on 2021-08-09 14:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0037_auto_20210618_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelplineNumbers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.Company')),
                ('component_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.Components')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
