# Generated by Django 3.0.3 on 2021-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0038_helplinenumbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helplinenumbers',
            name='hospital_id',
        ),
        migrations.AddField(
            model_name='helplinenumbers',
            name='hospital_ids',
            field=models.ManyToManyField(to='master_data.Hospital'),
        ),
        migrations.AlterField(
            model_name='helplinenumbers',
            name='contact_number',
            field=models.CharField(max_length=11),
        ),
    ]
