# Generated by Django 3.0.3 on 2021-08-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0039_auto_20210809_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='helplinenumbers',
            name='title',
            field=models.CharField(default='Helpline Numbers', max_length=255),
        ),
    ]
