# Generated by Django 3.0.3 on 2021-10-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0040_helplinenumbers_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='slot_blocking_duration',
            field=models.IntegerField(default=0),
        ),
    ]
