# Generated by Django 3.0.3 on 2021-11-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0041_hospital_slot_blocking_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='components',
            name='type',
            field=models.CharField(choices=[('hospital', 'hospital'), ('homecare', 'homecare')], default='hospital', max_length=30),
        ),
    ]
