# Generated by Django 3.0.3 on 2021-12-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0042_components_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='allow_refund_on_cancellation',
            field=models.BooleanField(default=True),
        ),
    ]
