# Generated by Django 3.0.3 on 2021-12-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0043_hospital_allow_refund_on_cancellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrecipients',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
