# Generated by Django 3.0.3 on 2020-03-14 07:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0011_auto_20200312_1234'),
        ('health_packages', '0006_auto_20200310_1101'),
        ('appointments', '0007_auto_20200312_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processing_id', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=50)),
                ('status', models.CharField(default='INITIAL', max_length=10)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('bank_ref_num', models.IntegerField(default=0, null=True)),
                ('settled_at', models.DateField()),
                ('raw_info_from_salucro_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.Appointment')),
                ('health_package', models.ManyToManyField(blank=True, null=True, to='health_packages.HealthPackage')),
                ('uhid_family_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.FamilyMember')),
                ('uhid_patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
