# Generated by Django 3.0.3 on 2020-03-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20200312_1234'),
        ('patients', '0011_auto_20200312_1234'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(default='42eeef7b-0b22-42d1-9ebd-500c1e9173b8', on_delete=django.db.models.deletion.PROTECT, related_name='payment_patient', to='patients.Patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.Appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uhid_family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.FamilyMember'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='uhid_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.Patient'),
        ),
    ]
