# Generated by Django 3.0.3 on 2020-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200314_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='uhid_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
