# Generated by Django 3.0.3 on 2020-03-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_uhid_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='health_package_appointment_status',
            field=models.CharField(default='Not Booked', max_length=10),
        ),
    ]
