# Generated by Django 3.0.3 on 2020-03-21 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0003_homecareservice'),
        ('payments', '0007_payment_health_package_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(default='Initiated', max_length=10),
        ),
    ]
