# Generated by Django 3.0.3 on 2020-03-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200321_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='health_package_appointment_status',
        ),
    ]
