# Generated by Django 3.0.3 on 2020-03-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_payment_health_package_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='health_package_appointment_status',
            field=models.CharField(default='Not Booked', max_length=10),
        ),
    ]
