# Generated by Django 3.0.3 on 2020-03-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_familymember_new_mobile'),
        ('payments', '0010_payment_health_package_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uhid_family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patients.FamilyMember'),
        ),
    ]
