# Generated by Django 3.0.3 on 2020-03-27 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_familymember_new_mobile'),
        ('payments', '0011_auto_20200326_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='uhid_family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.FamilyMember'),
        ),
    ]
