# Generated by Django 3.0.3 on 2020-03-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20200329_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='health_package_appointment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
