# Generated by Django 3.0.3 on 2020-03-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_auto_20200330_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='health_package_appointment_status',
            field=models.CharField(default='Not Booked', max_length=10),
        ),
    ]
