# Generated by Django 3.0.3 on 2020-04-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_patient_new_mobile_verification_otp'),
        ('payments', '0015_payment_health_package_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_done_for_family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.FamilyMember'),
        ),
    ]
