# Generated by Django 3.0.3 on 2020-04-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_auto_20200428_1857'),
        ('payments', '0017_auto_20200427_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='health_package_appointment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='health_package_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_health_package_appointment', to='appointments.HealthPackageAppointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_appointment', to='appointments.Appointment'),
        ),
    ]
