# Generated by Django 3.0.3 on 2020-04-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20200428_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='health_package',
        ),
    ]
