# Generated by Django 3.0.3 on 2020-05-04 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_ambulancecontact'),
        ('payments', '0020_payment_hospital_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment_hospital_key',
            new_name='PaymentHospitalKey',
        ),
    ]
