# Generated by Django 3.0.3 on 2020-06-02 13:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20200504_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uhid_number', models.CharField(blank=True, max_length=20, null=True)),
                ('processing_id', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('amount', models.FloatField(default=0, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
