# Generated by Django 3.0.3 on 2020-06-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_paymentrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrefund',
            name='request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
