# Generated by Django 3.0.3 on 2020-08-11 13:47

import apps.payments.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_auto_20200728_2254'),
        ('payments', '0025_auto_20200602_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uhid', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=500)),
                ('receipt', models.FileField(storage=utils.custom_storage.FileStorage(), upload_to=apps.payments.models.generate_receipt_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xml', 'dotx', 'pdf', 'txt', 'xls', 'xlsx', 'csv', 'ppt', 'pps', 'ppsx', 'bmp', 'jpg', 'jpeg', 'pjpeg', 'gif', 'png', 'svg', 'html']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity])),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('patient_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_receipt', to='patients.Patient')),
                ('payment_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipt', to='payments.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
