# Generated by Django 3.0.3 on 2020-12-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_paymentreceipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='invoice_id',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_id',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='int_payment_id',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='refund_id',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
