# Generated by Django 3.0.5 on 2021-01-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_auto_20201222_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
