# Generated by Django 3.0.5 on 2021-01-12 18:24

from django.db import migrations
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_auto_20210108_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthospitalkey',
            name='secret_secret',
            field=fernet_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
