# Generated by Django 3.0.3 on 2021-01-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_paymenthospitalkey_secret_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bill_row_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
