# Generated by Django 3.0.3 on 2021-03-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0033_auto_20210320_2313'),
        ('payments', '0033_auto_20210226_1559'),
    ]

    operations = [
    ]
