# Generated by Django 3.0.3 on 2021-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_merge_20210324_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_for_drive',
            field=models.BooleanField(default=False),
        ),
    ]
