# Generated by Django 3.0.3 on 2021-10-25 16:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0052_auto_20210331_1228'),
        ('patients', '0045_auto_20210615_1331'),
        ('payments', '0035_payment_payment_for_drive'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnprocessedTransactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('unprocessed', 'unprocessed'), ('processed', 'processed'), ('refunded', 'refunded')], default='unprocessed', max_length=100)),
                ('retries', models.IntegerField(default=0)),
                ('family_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.FamilyMember')),
                ('health_package_appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appointments.HealthPackageAppointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.Patient')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
