# Generated by Django 3.0.3 on 2021-10-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0059_auto_20211013_1543'),
        ('payments', '0036_unprocessedtransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='unprocessedtransactions',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unprocessed_transactions_appointment', to='appointments.Appointment'),
        ),
    ]
