# Generated by Django 3.0.3 on 2021-11-26 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0037_unprocessedtransactions_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unprocessedtransactions',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unprocessed_transactions_payment', to='payments.Payment'),
        ),
    ]
