# Generated by Django 3.0.2 on 2020-01-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='age',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
