# Generated by Django 3.0.2 on 2020-01-29 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(blank=True, choices=[('1', 'Father'), ('2', 'Mother'), ('3', 'Brother'), ('4', 'Sister'), ('5', 'Wife'), ('6', 'Husband'), ('7', 'Grand Father'), ('8', 'Grand Mother'), ('9', 'Others')], max_length=6, null=True, verbose_name='relation')),
                ('relative_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relative_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
    ]
