# Generated by Django 3.0.2 on 2020-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='favorite_hospital_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Favorite Hospital Code'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relation',
            field=models.IntegerField(blank=True, null=True, verbose_name='relation'),
        ),
    ]
