# Generated by Django 3.0.2 on 2020-01-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200114_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
