# Generated by Django 3.0.3 on 2020-02-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200211_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='profile_image',
            field=models.URLField(blank=True, null=True, verbose_name='Profile S3 Link'),
        ),
    ]
