# Generated by Django 3.0.2 on 2020-01-23 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200123_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='pin',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(9999)], verbose_name='Pin Number'),
        ),
    ]
