# Generated by Django 3.0.2 on 2020-02-04 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200114_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Id'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='favorite_hospital_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Favorite Hospital Code'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Id'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='mobile_verified',
            field=models.BooleanField(default=False, verbose_name='Mobile Verified'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Otp Number'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='otp_generate_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='otp generate time'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.IntegerField(blank=True, null=True, verbose_name='relation')),
                ('relative_user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relative_user', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
        ),
    ]
