# Generated by Django 3.0.2 on 2020-01-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_baseuser_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Pin Number'),
        ),
    ]
