# Generated by Django 3.0.2 on 2020-02-05 11:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200204_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Mobile Number'),
        ),
    ]
