# Generated by Django 3.0.2 on 2020-02-05 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200205_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relative_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
