# Generated by Django 3.0.2 on 2020-01-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200124_0758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='pin',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Otp Number'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='otp_generate_time',
            field=models.TimeField(auto_now=True, null=True, verbose_name='otp generate time'),
        ),
    ]
