# Generated by Django 3.0.2 on 2020-01-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200127_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseuser',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='baseuser',
            name='mobile_verified',
            field=models.BooleanField(default=False, verbose_name='Mobile Verified'),
        ),
        migrations.AlterField(
            model_name='baseuser',
            name='otp_generate_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='otp generate time'),
        ),
    ]
