# Generated by Django 3.0.2 on 2020-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200127_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='otp_generate_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='otp generate time'),
        ),
    ]
