# Generated by Django 3.0.2 on 2020-01-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200127_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Id'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Id'),
        ),
    ]
