# Generated by Django 3.0.3 on 2020-02-26 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManipalAdmin',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email Verified')),
            ],
            options={
                'verbose_name': 'Manipal Admin',
                'verbose_name_plural': 'Manipal Admin',
            },
            bases=('users.baseuser',),
        ),
    ]
