# Generated by Django 3.0.3 on 2020-02-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipal_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manipaladmin',
            name='role',
            field=models.IntegerField(default=1, verbose_name='Role'),
        ),
    ]
