# Generated by Django 3.0.3 on 2020-02-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manipal_admin', '0002_manipaladmin_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manipaladmin',
            name='role',
        ),
    ]
