# Generated by Django 3.0.3 on 2021-02-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manipal_admin', '0006_auto_20210216_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmenu',
            name='parent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manipal_admin.AdminMenu'),
        ),
    ]
