# Generated by Django 3.0.3 on 2021-02-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipal_admin', '0009_auto_20210218_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmenu',
            name='name',
            field=models.CharField(default='Admin menu', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='name',
            field=models.CharField(default='Admin Role', max_length=200, unique=True),
        ),
    ]
