# Generated by Django 3.0.3 on 2021-11-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipal_admin', '0010_auto_20210218_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='manipaladmin',
            name='secret_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='secret_key'),
        ),
        migrations.AddField(
            model_name='manipaladmin',
            name='secret_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='secret_token'),
        ),
    ]
