# Generated by Django 3.0.3 on 2022-03-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manipal_admin', '0011_auto_20211129_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='manipaladmin',
            name='isPcc',
            field=models.BooleanField(default=False),
        ),
    ]
