# Generated by Django 3.0.2 on 2020-01-17 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('relation', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
            },
            bases=('users.baseuser',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('associated_users', models.ManyToManyField(related_name='_patient_associated_users_+', to='patients.Patient')),
                ('relation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_relation', to='patients.Relationship')),
                ('reverse_relation_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reverse_relation', to='patients.Relationship')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'permissions': (),
            },
            bases=('users.baseuser',),
        ),
    ]
