# Generated by Django 3.0.3 on 2020-02-26 18:39

import apps.patients.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.custom_storage
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('master_data', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('baseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uhid_number', models.SlugField(blank=True, null=True, unique=True)),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middle Name')),
                ('facebook_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Id')),
                ('google_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Google Id')),
                ('display_picture', models.ImageField(blank=True, null=True, storage=utils.custom_storage.MediaStorage(), upload_to=apps.patients.models.generate_display_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'pjpeg', 'png', 'svg']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity], verbose_name='Profile Picture')),
                ('otp_expiration_time', models.DateTimeField(blank=True, null=True, verbose_name='OTP Key Expiration DateTime')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], max_length=6, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('mobile_verified', models.BooleanField(default=False, verbose_name='Mobile Verified')),
                ('is_primary_account', models.BooleanField(default=False)),
                ('favorite_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'permissions': (),
            },
            bases=('users.baseuser',),
        ),
        migrations.AddField(
            model_name='familymember',
            name='patient_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_family_member_info', to='patients.Patient'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('uhid_number', 'patient_info')},
        ),
    ]
