# Generated by Django 3.0.2 on 2020-01-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='associated_users',
            field=models.ManyToManyField(related_name='_patient_associated_users_+', to='patients.Patient'),
        ),
    ]
