# Generated by Django 3.0.3 on 2020-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200226_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='alpha@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
    ]
