# Generated by Django 3.0.3 on 2020-02-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200227_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvalidateuhid',
            name='otp_expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP Key Expiration DateTime'),
        ),
    ]
