# Generated by Django 3.0.3 on 2020-02-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientvalidateuhid_otp_expiration_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientValidateUHID',
            new_name='PatientUHID',
        ),
        migrations.AlterModelOptions(
            name='patientuhid',
            options={'verbose_name': 'Patient UHID', 'verbose_name_plural': 'Patient UHID'},
        ),
    ]
