# Generated by Django 3.0.3 on 2020-02-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_auto_20200227_0814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientuhid',
            options={'verbose_name': 'Patient UHID', 'verbose_name_plural': 'Patient UHIDs'},
        ),
    ]
