# Generated by Django 3.0.3 on 2020-02-27 11:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20200227_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mobile_verified',
            field=models.BooleanField(default=False, verbose_name='Mobile Verified'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='raw_info_from_manipal_API',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
