# Generated by Django 3.0.3 on 2020-02-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_auto_20200227_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='is_primary_account',
        ),
        migrations.AddField(
            model_name='familymember',
            name='email_otp_expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email OTP Key Expiration DateTime'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='email_verification_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mobile_otp_expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Mobile OTP Key Expiration DateTime'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='mobile_verification_otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='PatientUHID',
        ),
    ]
