# Generated by Django 3.0.3 on 2020-03-11 10:52

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20200228_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pincode_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(999999)])),
                ('house_details', models.CharField(max_length=500)),
                ('area_details', models.CharField(max_length=500)),
                ('address_type', models.CharField(blank=True, choices=[('Home Address', 'Home Address'), ('Work/Office Address', 'Work/Office Address')], default='Home Address', max_length=20, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, default=django.contrib.gis.geos.point.Point(1, 1), null=True, srid=4326)),
                ('patient_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_address_info', to='patients.Patient')),
            ],
            options={
                'verbose_name': 'Patient Address',
                'verbose_name_plural': 'Patient Addresses',
            },
        ),
    ]
