# Generated by Django 3.0.3 on 2020-03-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_patientaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='pre_registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='pre_registration_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
