# Generated by Django 3.0.3 on 2020-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20200312_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
