# Generated by Django 3.0.3 on 2020-03-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_familymember_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email_otp_expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email OTP Key Expiration DateTime'),
        ),
    ]
