# Generated by Django 3.0.3 on 2020-03-24 06:37

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_auto_20200323_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='new_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='New Mobile Number'),
        ),
    ]
