# Generated by Django 3.0.3 on 2020-04-02 04:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_familymember_new_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='new_mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='New Mobile Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='new_mobile_otp_expiration_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='New mobile OTP Key Expiration DateTime'),
        ),
    ]
