# Generated by Django 3.0.3 on 2020-04-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0005_country_idproof_province_region'),
        ('patients', '0016_patient_new_mobile_verification_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='relation_name',
        ),
        migrations.AddField(
            model_name='familymember',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_family_member_relation', to='patient_registration.Relation'),
            preserve_default=False,
        ),
    ]
