# Generated by Django 3.0.3 on 2020-04-15 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20200415_1127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familymember',
            old_name='relation',
            new_name='relationship',
        ),
    ]
