# Generated by Django 3.0.5 on 2020-04-18 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_registration', '0005_country_idproof_province_region'),
        ('patients', '0018_auto_20200415_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_family_member_relation', to='patient_registration.Relation'),
        ),
    ]
