# Generated by Django 3.0.3 on 2020-07-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20200418_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='apple_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='apple_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apple Id'),
        ),
    ]
