# Generated by Django 3.0.3 on 2020-10-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_auto_20201013_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_corporate',
            field=models.BooleanField(default=False, verbose_name='is_corporate'),
        ),
    ]
