# Generated by Django 3.0.3 on 2020-10-27 11:53

from django.db import migrations, models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_patient_is_corporate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpGenerationCount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Mobile Number')),
                ('otp_generation_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'verbose_name': 'Patient Otp Count',
                'verbose_name_plural': 'Patient Otp Counts',
            },
        ),
    ]
