# Generated by Django 3.0.3 on 2021-03-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0029_auto_20210309_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidvaccinationregistration',
            name='family_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_member_covid_registration', to='patients.FamilyMember'),
        ),
    ]
