# Generated by Django 3.0.3 on 2021-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_auto_20210309_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidvaccinationregistration',
            name='id',
        ),
        migrations.AlterField(
            model_name='covidvaccinationregistration',
            name='registration_no',
            field=models.PositiveIntegerField(default=100000, editable=False, primary_key=True, serialize=False),
        ),
    ]
