# Generated by Django 3.0.3 on 2021-03-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0034_auto_20210309_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidvaccinationregistration',
            name='registration_no',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
