# Generated by Django 3.0.3 on 2021-03-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_auto_20210309_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidvaccinationregistration',
            name='vaccination_slot',
            field=models.TimeField(blank=True, null=True, verbose_name='Time slot of vaccination'),
        ),
    ]
