# Generated by Django 3.0.3 on 2021-03-23 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0037_auto_20210322_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='aadhar_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
        migrations.AddField(
            model_name='patient',
            name='aadhar_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000000000), django.core.validators.MaxValueValidator(999999999999)]),
        ),
    ]
