# Generated by Django 3.0.3 on 2021-04-28 13:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0031_merge_20210428_1328'),
        ('patients', '0042_familymember_is_corporate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMemberCorporateHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_family_member_company_info', to='master_data.Company')),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_family_member_corporate_history', to='patients.FamilyMember')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
