# Generated by Django 3.0.3 on 2021-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0043_familymembercorporatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='is_corporate',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='is_corporate'),
        ),
    ]
