# Generated by Django 3.0.3 on 2021-09-24 12:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0045_auto_20210615_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatePatientMobile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uhid_number', models.CharField(max_length=20)),
                ('new_patient_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_patient_user', to='patients.Patient')),
                ('old_patient_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_patient_user', to='patients.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
