# Generated by Django 3.0.3 on 2021-10-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0046_updatepatientmobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_birthday_notification_on',
            field=models.BooleanField(default=True, verbose_name='is_birthday_notification_on'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_promotional_notification_on',
            field=models.BooleanField(default=True, verbose_name='is_promotional_notification_on'),
        ),
    ]
