# Generated by Django 3.0.3 on 2021-11-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0042_components_type'),
        ('patients', '0047_auto_20211005_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='corporate_favorite_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_favorite_hospital', to='master_data.Hospital'),
        ),
    ]
