# Generated by Django 3.0.3 on 2021-06-10 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticInstructions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instruction_type', models.CharField(max_length=50)),
                ('instruction', models.TextField()),
                ('sequence', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
