# Generated by Django 3.0.3 on 2021-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0003_auto_20210611_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='booking_start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
