# Generated by Django 3.0.3 on 2021-06-14 10:54

import apps.additional_features.models
import datetime
import django.core.validators
from django.db import migrations, models
import django_clamd.validators
import utils.custom_storage
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0006_auto_20210611_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='booking_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 10, 54, 2, 958793)),
        ),
        migrations.AlterField(
            model_name='drive',
            name='booking_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 10, 54, 2, 958756)),
        ),
        migrations.AlterField(
            model_name='drive',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=utils.custom_storage.MediaStorage(), upload_to=apps.additional_features.models.generate_qr_code_picture_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'pjpeg', 'png', 'svg']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity, django_clamd.validators.validate_file_infection], verbose_name='display_QR_code'),
        ),
    ]
