# Generated by Django 3.0.3 on 2021-06-14 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0007_auto_20210614_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='booking_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 11, 29, 35, 369205)),
        ),
        migrations.AlterField(
            model_name='drive',
            name='booking_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 11, 29, 35, 369167)),
        ),
        migrations.AlterField(
            model_name='drive',
            name='code',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
