# Generated by Django 3.0.3 on 2021-06-15 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0009_auto_20210614_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveinventory',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='booking_end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 10, 11, 50, 931303)),
        ),
        migrations.AlterField(
            model_name='drive',
            name='booking_start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 15, 10, 11, 50, 931258)),
        ),
    ]
