# Generated by Django 3.0.3 on 2021-06-15 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0010_auto_20210614_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveinventory',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        )
    ]
