# Generated by Django 3.0.3 on 2021-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0011_auto_20210615_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivebooking',
            name='drive_corporate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
