# Generated by Django 3.0.3 on 2021-06-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0012_drivebooking_drive_corporate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivebooking',
            name='dose',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
