# Generated by Django 3.0.3 on 2021-06-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0013_drivebooking_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivebooking',
            name='beneficiary_reference_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
