# Generated by Django 3.0.3 on 2021-06-18 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0014_drivebooking_beneficiary_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
