# Generated by Django 3.0.3 on 2021-07-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additional_features', '0017_auto_20210630_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='description',
            field=models.TextField(unique=True),
        ),
    ]
