# Generated by Django 3.0.3 on 2020-06-10 18:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0027_healthpackageappointment_other_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=200, verbose_name='Room Name')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.Appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
