# Generated by Django 3.0.3 on 2020-06-10 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_conferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoconference',
            name='recording_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
