# Generated by Django 3.0.3 on 2020-03-16 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0008_auto_20200313_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uhid', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('doctor_name', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='TextReportDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('observation_value', models.TextField(max_length=10000000)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
            options={
                'verbose_name': 'Text Report Detail',
                'verbose_name_plural': 'Text Report Details',
            },
        ),
        migrations.CreateModel(
            name='StringReportDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('observation_value', models.CharField(max_length=100)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
            options={
                'verbose_name': 'String Report Detail',
                'verbose_name_plural': 'String Report Details',
            },
        ),
        migrations.CreateModel(
            name='NumericReportDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('observation_value', models.CharField(max_length=100)),
                ('observation_range', models.CharField(max_length=100)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.Report')),
            ],
            options={
                'verbose_name': 'Numeric Report Detail',
                'verbose_name_plural': 'Numeric Report Details',
            },
        ),
    ]
