# Generated by Django 3.0.3 on 2020-03-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200330_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient_class',
            field=models.CharField(choices=[('E', 'Emergency'), ('O', 'Outpatient'), ('I', 'Inpatient')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='visit_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
