# Generated by Django 3.0.3 on 2020-03-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200331_0700'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message_id',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
