# Generated by Django 3.0.3 on 2020-03-31 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0005_auto_20200325_0642'),
        ('reports', '0004_report_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital'),
        ),
    ]
