# Generated by Django 3.0.3 on 2020-04-03 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textreportdetails',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='text_report', to='reports.Report'),
        ),
    ]
