# Generated by Django 3.0.3 on 2020-04-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200403_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stringreportdetails',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='string_report', to='reports.Report'),
        ),
    ]
