# Generated by Django 3.0.3 on 2020-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200403_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numericreportdetails',
            name='observation_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
