# Generated by Django 3.0.3 on 2020-04-13 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20200413_0644'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeTextReportDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('observation_value', models.CharField(max_length=10000000)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='free_text_report', to='reports.Report')),
            ],
            options={
                'verbose_name': 'Free TextReport Detail',
                'verbose_name_plural': 'Free TextReport Details',
            },
        ),
    ]
