# Generated by Django 3.0.6 on 2020-06-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_freetextreportdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericreportdetails',
            name='observation_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
