# Generated by Django 3.0.3 on 2020-08-19 11:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_reportdocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uhid', models.CharField(max_length=20)),
                ('visit_id', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
