# Generated by Django 3.0.3 on 2020-08-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_visitreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='patient_class',
            field=models.CharField(default='I', max_length=100),
            preserve_default=False,
        ),
    ]
