# Generated by Django 3.0.3 on 2020-08-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_visitreport_patient_class'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitreport',
            options={'verbose_name': 'Report Visit', 'verbose_name_plural': 'Report Visits'},
        ),
        migrations.AddField(
            model_name='report',
            name='report_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reports.VisitReport'),
        ),
    ]
