# Generated by Django 3.0.3 on 2020-09-08 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20200827_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='visit_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
