# Generated by Django 3.0.3 on 2020-09-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_report_visit_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='place_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
