# Generated by Django 3.0.3 on 2020-09-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_report_place_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='Lab', max_length=20),
        ),
    ]
