# Generated by Django 3.0.3 on 2020-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_report_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='patient_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
