# Generated by Django 3.0.3 on 2020-10-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_report_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitreport',
            name='patient_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
