# Generated by Django 3.0.3 on 2020-03-14 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0003_homecareservice'),
        ('health_packages', '0006_auto_20200310_1101'),
        ('patients', '0011_auto_20200312_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthPackageCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('health_packages', models.ManyToManyField(blank=True, null=True, to='health_packages.HealthPackage')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital')),
                ('patient_info', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient_health_package_cart', to='patients.Patient')),
            ],
            options={
                'verbose_name': 'Health Package Cart',
                'verbose_name_plural': 'Health Packages Cart',
            },
        ),
    ]
