# Generated by Django 3.0.3 on 2020-03-16 16:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20200312_1234'),
        ('master_data', '0003_homecareservice'),
        ('lab_and_radiology_items', '0005_uploadprescription'),
        ('health_packages', '0006_auto_20200310_1101'),
        ('cart_items', '0002_auto_20200314_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackagecart',
            name='health_packages',
            field=models.ManyToManyField(blank=True, to='health_packages.HealthPackage'),
        ),
        migrations.CreateModel(
            name='HomeCollectionCart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_collections', models.ManyToManyField(blank=True, to='lab_and_radiology_items.LabRadiologyItem')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master_data.Hospital')),
                ('patient_info', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient_home_collection_cart', to='patients.Patient')),
            ],
            options={
                'verbose_name': 'Home Collection Cart',
                'verbose_name_plural': 'Home Collections Cart',
            },
        ),
    ]
