# Generated by Django 3.0.2 on 2020-01-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='end_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
