# Generated by Django 3.0.3 on 2020-03-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20200312_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='awards_achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fellowship_membership',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='field_expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
