# Generated by Django 3.0.3 on 2020-03-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20200312_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
