# Generated by Django 3.0.3 on 2020-03-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20200313_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='languages_spoken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
