# Generated by Django 3.0.3 on 2020-07-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_auto_20200313_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='consultation_charges',
            new_name='hv_consultation_charges',
        ),
        migrations.AddField(
            model_name='doctor',
            name='pr_consultation_charges',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='vc_consultation_charges',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
