# Generated by Django 3.0.3 on 2020-07-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_homecareservice_image'),
        ('doctors', '0010_doctor_is_online_appointment_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='hospital_departments',
            field=models.ManyToManyField(blank=True, related_name='doctor_hospital_department', to='master_data.HospitalDepartment'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialisations',
            field=models.ManyToManyField(blank=True, related_name='doctor_specialisation', to='master_data.Specialisation'),
        ),
    ]
