# Generated by Django 3.0.3 on 2020-08-13 02:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0007_homecareservice_image'),
        ('doctors', '0011_auto_20200718_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCharges',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hv_consultation_charges', models.IntegerField(default=0, null=True)),
                ('vc_consultation_charges', models.IntegerField(default=0, null=True)),
                ('pr_consultation_charges', models.IntegerField(default=0, null=True)),
                ('department_info', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_hospital_department_charges', to='master_data.Department')),
                ('doctor_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Consultation Charges',
                'verbose_name_plural': 'Consultation charges',
            },
        ),
    ]
