# Generated by Django 3.0.3 on 2021-08-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0016_doctorsweeklyschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='service',
        ),
        migrations.AddField(
            model_name='doctorsweeklyschedule',
            name='service',
            field=models.CharField(blank=True, choices=[('HV', 'HV'), ('VC', 'VC'), ('HVVC', 'HVVC')], max_length=6, null=True),
        ),
    ]
