# Generated by Django 3.0.3 on 2021-09-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_auto_20210813_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorsweeklyschedule',
            options={'verbose_name': 'Weekly Schedule', 'verbose_name_plural': 'Weekly Schedules'},
        ),
        migrations.AlterField(
            model_name='doctorsweeklyschedule',
            name='service',
            field=models.CharField(blank=True, choices=[('HV', 'HV'), ('VC', 'VC'), ('HVVC', 'HVVC'), ('HV/VC', 'HV/VC'), ('PR', 'PR')], max_length=6, null=True),
        ),
    ]
