# Generated by Django 3.0.2 on 2020-02-14 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
        ('master_data', '0001_initial'),
        ('appointments', '0002_auto_20200207_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='token_no',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentIdentifier',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='req_patient',
            field=models.ForeignKey(default='15d98c53-f311-437a-bc8d-3c5a41139b5f', on_delete=django.db.models.deletion.CASCADE, related_name='req_patient', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='doctors.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='master_data.Hospital'),
        ),
    ]
