# Generated by Django 3.0.3 on 2020-03-02 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20200228_1110'),
        ('appointments', '0003_auto_20200227_0751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='time_slot_from',
            new_name='appointment_slot',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='req_patient',
            new_name='patient',
        ),
        migrations.AddField(
            model_name='appointment',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_appointment', to='patients.FamilyMember'),
        ),
    ]
