# Generated by Django 3.0.3 on 2020-02-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20200214_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentIdentifier',
            field=models.IntegerField(default=1235678),
            preserve_default=False,
        ),
    ]
