# Generated by Django 3.0.3 on 2020-02-18 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0002_auto_20200217_1006'),
        ('master_data', '0001_initial'),
        ('appointments', '0004_auto_20200218_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctor', to='doctors.Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hospital', to='master_data.Hospital'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='req_patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='req_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
