# Generated by Django 3.0.3 on 2020-03-03 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20200302_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointmentIdentifier',
            new_name='appointment_identifier',
        ),
    ]
