# Generated by Django 3.0.3 on 2020-03-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20200306_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_identifier',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
