# Generated by Django 3.0.3 on 2020-03-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20200312_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
