# Generated by Django 3.0.3 on 2020-03-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_familymember_new_mobile'),
        ('appointments', '0011_auto_20200325_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='uhid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family_appointment', to='patients.FamilyMember'),
        ),
    ]
