# Generated by Django 3.0.3 on 2020-04-25 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20200404_1713'),
        ('appointments', '0015_auto_20200413_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthpackageappointment',
            name='health_package',
        ),
        migrations.AlterField(
            model_name='healthpackageappointment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.Payment'),
        ),
    ]
