# Generated by Django 3.0.3 on 2020-04-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20200418_0741'),
        ('appointments', '0016_auto_20200425_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackageappointment',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='family_health_package_appointment', to='patients.FamilyMember'),
        ),
        migrations.AddField(
            model_name='healthpackageappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_health_package_appointment', to='patients.Patient'),
            preserve_default=False,
        ),
    ]
