# Generated by Django 3.0.3 on 2020-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_auto_20200425_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthpackageappointment',
            name='appointment_slot',
        ),
        migrations.AlterField(
            model_name='healthpackageappointment',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
