# Generated by Django 3.0.3 on 2020-04-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_auto_20200427_2134'),
        ('appointments', '0018_auto_20200426_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpackageappointment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_health_package_appointment', to='payments.Payment'),
        ),
    ]
