# Generated by Django 3.0.3 on 2020-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_packages', '0007_healthpackage_is_popular'),
        ('appointments', '0019_auto_20200428_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackageappointment',
            name='health_package',
            field=models.ManyToManyField(blank=True, null=True, to='health_packages.HealthPackage'),
        ),
    ]
