# Generated by Django 3.0.3 on 2020-05-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_ambulancecontact'),
        ('appointments', '0020_healthpackageappointment_health_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultation_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospital_department', to='master_data.Hospital'),
        ),
    ]
