# Generated by Django 3.0.3 on 2020-05-06 16:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_auto_20200502_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackageappointment',
            name='health_package_original',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
