# Generated by Django 3.0.3 on 2020-05-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_healthpackageappointment_health_package_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Confirmed'), (2, 'Cancelled'), (3, 'Waiting'), (4, 'Completed'), (5, 'Rescheduled'), (6, 'Rebooked')]),
        ),
    ]
