# Generated by Django 3.0.3 on 2020-05-27 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_auto_20200513_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='refundable_amount',
            field=models.FloatField(default=0, null=True),
        ),
    ]
