# Generated by Django 3.0.3 on 2020-05-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0025_appointment_refundable_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='other_reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
