# Generated by Django 3.0.3 on 2020-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_appointment_other_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackageappointment',
            name='other_reason',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
