# Generated by Django 3.0.3 on 2020-06-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0027_healthpackageappointment_other_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_mode',
            field=models.CharField(default='HV', max_length=10),
        ),
    ]
