# Generated by Django 3.0.3 on 2020-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0029_appointment_enable_join_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vc_appointment_status',
            field=models.IntegerField(default='1'),
        ),
    ]
