# Generated by Django 3.0.3 on 2020-06-23 13:04

import apps.appointments.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0030_appointment_vc_appointment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('document', models.FileField(storage=utils.custom_storage.FileStorage(), upload_to=apps.appointments.models.generate_personal_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xml', 'dotx', 'pdf', 'txt', 'xls', 'xlsx', 'csv', 'ppt', 'pps', 'ppsx', 'bmp', 'jpg', 'jpeg', 'pjpeg', 'gif', 'png', 'svg', 'html']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity])),
                ('appointment_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_documents', to='appointments.Appointment')),
            ],
            options={
                'verbose_name': 'Appointment Document',
                'verbose_name_plural': 'Appointment Documents',
            },
        ),
    ]
