# Generated by Django 3.0.3 on 2020-06-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0031_appointmentdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient_ready',
            field=models.BooleanField(default=False),
        ),
    ]
