# Generated by Django 3.0.3 on 2020-06-23 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0034_remove_appointmentdocuments_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentVital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=15, null=True)),
                ('body_temperature', models.CharField(blank=True, max_length=15, null=True)),
                ('appointment_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_vitals', to='appointments.Appointment')),
            ],
            options={
                'verbose_name': 'Appointment Vital',
                'verbose_name_plural': 'Appointment Vitals',
            },
        ),
    ]
