# Generated by Django 3.0.3 on 2020-07-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0036_auto_20200712_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentvital',
            name='height',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='appointmentvital',
            name='weight',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
