# Generated by Django 3.0.3 on 2020-07-16 15:11

import apps.appointments.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0037_auto_20200713_0248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentvital',
            options={'verbose_name': 'Appointment Prescription', 'verbose_name_plural': 'Appointment Prescriptions'},
        ),
        migrations.CreateModel(
            name='PrescriptionDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('prescription', models.FileField(storage=utils.custom_storage.FileStorage(), upload_to=apps.appointments.models.generate_prescription_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xml', 'dotx', 'pdf', 'txt', 'xls', 'xlsx', 'csv', 'ppt', 'pps', 'ppsx', 'bmp', 'jpg', 'jpeg', 'pjpeg', 'gif', 'png', 'svg', 'html']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity])),
                ('appointment_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_presciptions', to='appointments.Appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
