# Generated by Django 3.0.3 on 2020-07-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0038_auto_20200716_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentvital',
            options={'verbose_name': 'Appointment Document', 'verbose_name_plural': 'Appointment Documents'},
        ),
        migrations.AlterModelOptions(
            name='prescriptiondocuments',
            options={'verbose_name': 'Appointment Prescription', 'verbose_name_plural': 'Appointment Prescriptions'},
        ),
    ]
