# Generated by Django 3.0.3 on 2020-08-06 23:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_auto_20200728_2254'),
        ('appointments', '0040_auto_20200717_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.TextField(max_length=100)),
                ('rating', models.IntegerField(default='1')),
                ('platform', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=20)),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_user', to='patients.Patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
