# Generated by Django 3.0.3 on 2020-09-10 15:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0041_feedbacks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPrescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_prescription', to='appointments.Appointment')),
                ('prescription_documents', models.ManyToManyField(blank=True, null=True, to='appointments.PrescriptionDocuments')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
