# Generated by Django 3.0.3 on 2020-10-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0042_appointmentprescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='corporate_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
