# Generated by Django 3.0.3 on 2020-12-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0043_appointment_corporate_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
