# Generated by Django 3.0.3 on 2021-02-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0045_appointment_plan_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacks',
            name='feedback',
            field=models.TextField(max_length=500),
        ),
    ]
