# Generated by Django 3.0.3 on 2021-03-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0046_auto_20210211_2153'),
        ('appointments', '0046_auto_20210203_1644'),
    ]

    operations = [
    ]
