# Generated by Django 3.0.3 on 2021-03-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0047_auto_20210226_1559'),
        ('appointments', '0047_merge_20210318_1513'),
    ]

    operations = [
    ]
