# Generated by Django 3.0.3 on 2021-03-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0048_auto_20210320_2313'),
        ('appointments', '0048_merge_20210323_1351'),
    ]

    operations = [
    ]
