# Generated by Django 3.0.3 on 2021-03-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0049_merge_20210324_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='beneficiary_reference_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
