# Generated by Django 3.0.3 on 2021-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0050_appointment_beneficiary_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(default='consultation', max_length=20),
        ),
    ]
