# Generated by Django 3.0.3 on 2021-03-31 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0051_appointment_appointment_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_type',
            new_name='appointment_service',
        ),
    ]
