# Generated by Django 3.0.3 on 2021-10-13 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0040_helplinenumbers_title'),
        ('appointments', '0052_auto_20210331_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimeBenefits',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('hospital_info', models.ManyToManyField(blank=True, null=True, related_name='prime_benefits_hospital', to='master_data.Hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
