# Generated by Django 3.0.3 on 2021-09-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0052_auto_20210331_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='root_appointment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
