# Generated by Django 3.0.3 on 2021-09-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0053_appointment_root_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_duration',
            field=models.IntegerField(default=10),
        ),
    ]
