# Generated by Django 3.0.3 on 2021-09-27 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0054_appointment_appointment_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='appointment_duration',
            new_name='slot_duration',
        ),
    ]
