# Generated by Django 3.0.3 on 2021-09-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0056_remove_appointment_slot_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot_duration',
            field=models.FloatField(default=10),
        ),
    ]
