# Generated by Django 3.0.3 on 2021-10-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0058_primebenefits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='primebenefits',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
