# Generated by Django 3.0.3 on 2020-09-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge_summaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='visit_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
