# Generated by Django 3.0.3 on 2020-09-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge_summaries', '0002_dischargesummary_visit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargesummary',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dischargesummary',
            name='file_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
