# Generated by Django 3.0.3 on 2020-04-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='device_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
