# Generated by Django 3.0.3 on 2020-05-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200409_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiledevice',
            name='version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
