# Generated by Django 3.0.3 on 2021-06-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20210531_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilenotification',
            name='notification_image',
        ),
        migrations.AddField(
            model_name='mobilenotification',
            name='notification_image_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Notification Image Url'),
        ),
    ]
