# Generated by Django 3.0.3 on 2021-09-28 16:10

import apps.notifications.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_clamd.validators
import utils.custom_storage
import utils.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20210601_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_subject', models.CharField(max_length=500)),
                ('notification_body', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleNotifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uhids', models.TextField()),
                ('file', models.FileField(storage=utils.custom_storage.FileStorage(), upload_to=apps.notifications.models.generate_notification_uhids_file_path, validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'xml', 'dotx', 'pdf', 'txt', 'xls', 'xlsx', 'csv', 'ppt', 'pps', 'ppsx', 'bmp', 'jpg', 'jpeg', 'pjpeg', 'gif', 'png', 'svg', 'html']), utils.validators.validate_file_size, utils.validators.validate_file_authenticity, django_clamd.validators.validate_file_infection])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_scheduled', models.BooleanField(default=True)),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_template_id', to='notifications.NotificationTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
