# Generated by Django 3.0.3 on 2021-09-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notificationtemplate_schedulenotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulenotifications',
            name='trigger_type',
            field=models.CharField(choices=[('schedule', 'schedule'), ('now', 'now')], default='schedule', max_length=10),
        ),
    ]
