# Generated by Django 3.0.3 on 2021-10-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_schedulenotifications_trigger_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulenotifications',
            name='is_scheduled',
        ),
        migrations.AddField(
            model_name='schedulenotifications',
            name='is_executed',
            field=models.BooleanField(default=False),
        ),
    ]
