# Generated by Django 3.0.3 on 2021-10-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20211006_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulenotifications',
            name='schedule_type',
            field=models.CharField(choices=[('promotional', 'promotional'), ('transactional', 'transactional')], default='transactional', max_length=20),
        ),
    ]
